# Generated by Django 5.2 on 2025-04-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Amount', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(blank=True, max_length=200, null=True)),
                ('CreatedAt', models.CharField(blank=True, max_length=100, null=True)),
                ('UpdatedAt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
